(G-code generated by SimplePostProcessor)
G21 
(Set units to millimeters)
G17G90
(Set XY plane and absolute positioning)
(Tool: D = 3.0 mm  type BALLNOSE flutes 2)
S12000M03
(Spindle speed 12000 RPM, clockwise rotation)
G00 Z10.0
G00 X-0.050000012 Y-0.050000012
G01 Z0 F1000
X-0.050000012 Y-0.050000012 Z-5.9
X0.050000012 Y0.35 Z-5.9
X-0.050000012 Y0.050000012 Z-5.9
X0.35 Y-0.050000012 Z-5.9
G00 Z10.0
M05
(Spindle stop)
G00 X0 Y0
(Return to home position)
M30
(End of program)
